# Generated by Django 5.0.6 on 2024-05-10 17:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employeedetails",
            name="mobile_number",
            field=models.BigIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1000000000),
                    django.core.validators.MaxValueValidator(9999999999),
                ]
            ),
        ),
    ]
