# Generated by Django 5.0.6 on 2024-05-11 18:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0002_alter_employeedetails_mobile_number"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="EmployeeDetails",
            new_name="EmployeeDetail",
        ),
    ]
