# Generated by Django 5.0.6 on 2024-05-11 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0003_rename_employeedetails_employeedetail"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeedetail",
            name="approved",
            field=models.BooleanField(default=False),
        ),
    ]
