# Generated by Django 5.0.6 on 2024-05-14 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0004_employeedetail_approved"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employeedetail",
            name="approved",
        ),
    ]
