# Generated by Django 5.0.6 on 2024-05-14 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0005_remove_employeedetail_approved"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeedetail",
            name="approved",
            field=models.BooleanField(default=False),
        ),
    ]
