# Generated by Django 5.0.6 on 2024-05-15 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0006_employeedetail_approved"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employeedetail",
            name="approved",
        ),
    ]
