# Generated by Django 5.0.6 on 2024-05-15 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0007_remove_employeedetail_approved"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="activity_date",
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name="activity",
            name="activity_time",
            field=models.DateTimeField(default=None),
        ),
    ]
