# Generated by Django 5.0.6 on 2024-05-15 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0008_activity_activity_date_alter_activity_activity_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="activity_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="activity",
            name="activity_time",
            field=models.TimeField(),
        ),
    ]
