# Generated by Django 5.0.6 on 2024-05-16 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0010_alter_activity_activity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="activity",
            field=models.CharField(
                choices=[
                    ("Punch In", "Start My Day"),
                    ("Punch Out", "End My Day"),
                    ("Signout", "Signout"),
                ],
                max_length=100,
            ),
        ),
    ]
