# Generated by Django 5.0.6 on 2024-05-16 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0011_alter_activity_activity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="activity",
            name="activity_date",
        ),
        migrations.RemoveField(
            model_name="activity",
            name="activity_time",
        ),
        migrations.AddField(
            model_name="activity",
            name="activity_at",
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
    ]
